In [1]:
import pandas as pd

players_2020 = pd.read_csv('2020.csv')
players_2021 = pd.read_csv('2021.csv')
players_2022 = pd.read_csv('2022.csv')
fm = pd.read_csv('players.csv')

In [2]:
fm = fm.drop(['Unnamed: 0','DoB'], axis=1).dropna()

In [3]:
player_stats_2022 = pd.merge(fm,players_2022,on=['Player','Based','Born'])

#begin fixing missing/incorrect data
#drop duplicate players
player_stats_2022 = player_stats_2022.drop_duplicates('UID')

#remove players with first letter of squad and club columns not the same
dup = player_stats_2022[player_stats_2022.duplicated(['Player'], keep=False)]
dup_players = dup['Player'].tolist()
for i in dup_players:
    player_stats_2022 = player_stats_2022.loc[~((player_stats_2022['Player'] == i) & (player_stats_2022.Club.str[0]!=player_stats_2022.Squad.str[0]))]

# #drop special cases
final_players_2022 = player_stats_2022.drop_duplicates( 
  subset = ['Player','Born','Squad','Club'], 
  keep = 'last').reset_index(drop = True) 

# #final player stat dataset with correct unique player data
final_players_2022

,UID,Player,Nat,Club,Based,Preferred Foot,Height (cm),Weight (kg),birth_month,Born,...,Medium Att,Medium Cmp%,Long Cmp,Long Att,Long Cmp%,Ast,xAG,xA,KP,PrgP
0,831079,Giorgio Chiellini,ITA,LAFC,U.S.A. (MLS),Left Only,187,85,8,1984,...,218,88.5,46,78,59.0,1,0.5,0.4,2,51
1,2105510,Hulk,BRA,ATM,Brazil (First Division),Left,179,95,7,1986,...,162,70.4,30,62,48.4,2,3.4,3.9,40,67
2,962988,Gonzalo Higuaín,ARG,Inter Miami,U.S.A. (MLS),Right,184,89,12,1987,...,165,79.4,59,109,54.1,3,3.6,3.1,34,44
3,8825061,Fernandinho,BRA,ATP,Brazil (First Division),Right,179,67,5,1985,...,234,86.3,50,70,71.4,2,1.8,1.8,21,108
4,5132312,Gareth Bale,WAL,LAFC,U.S.A. (MLS),Left,185,82,7,1989,...,42,81.0,12,17,70.6,0,0.6,0.4,6,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7397,2000131318,Pablo Marín,ESP,Real San Sebastián,Spain (First Division),Right,186,76,7,2003,...,48,75.0,9,12,75.0,0,0.8,0.4,6,15
7398,67287574,Raúl Parra,ESP,Mirandés,Spain (Second Division),Either,187,78,11,1999,...,250,72.4,70,157,44.6,0,0.6,0.8,9,53
7399,2000165970,Pau Sans,ESP,Zaragoza,Spain (Second Division),Right,183,69,11,2004,...,6,33.3,0,1,0.0,0,0.0,0.0,1,1
7400,2000209777,Pablo Muñoz,ESP,Vallecano,Spain (First Division),Right,170,60,9,2003,...,0,0.0,0,0,0.0,0,0.0,0.0,0,1
7401,2000209781,Diego Méndez,ESP,Vallecano,Spain (First Division),Right Only,189,79,8,2003,...,0,0.0,0,0,0.0,0,0.0,0.0,0,0

In [4]:
phys_stats = final_players_2022[['UID', 'Player', 'Nat', 'Preferred Foot',
       'Height (cm)', 'Weight (kg)', 'birth_month', 'Born', 'Club']]
player_stats_2021 = pd.merge(phys_stats,players_2021,on=['Player','Born'])
dups = player_stats_2021[player_stats_2021.duplicated(['UID'], keep=False)]
dups[['Player','Club','Squad']]

#remove duplicate players
dup = player_stats_2021[player_stats_2021.duplicated(['UID'], keep=False)]

dup['Player']
dup_players = dup['Player'].tolist()
for i in dup_players:
    player_stats_2021 = player_stats_2021.loc[~((player_stats_2021['Player'] == i) & (player_stats_2021.Club.str[0]!=player_stats_2021.Squad.str[0]))]
    dup = dup.loc[~((dup['Player'] == i) & (dup.Club.str[0]!=dup.Squad.str[0]))]

dup2 = dup[dup.duplicated(['UID'], keep=False)]
dup_players2 = dup2['Player'].tolist()
for i in dup_players2:
    final_players_2021 = player_stats_2021.loc[~((player_stats_2021['Player'] == i) & (player_stats_2021.Club.str[0:2]!=player_stats_2021.Squad.str[0:2]))]
    
#drop any remaining duplicate players
final_players_2021 = final_players_2021.drop_duplicates('UID').drop(['Unnamed: 0','Total Cmp','Total Att', 
                                                                     'Total Cmp%','Short Att','Medium Att',
                                                                     'Long Att','Tkl', 'Sh','Squad','SoT','Based'], axis=1)
final_players_2021.columns

Index(['UID', 'Player', 'Nat', 'Preferred Foot', 'Height (cm)', 'Weight (kg)',
       'birth_month', 'Born', 'Club', 'Age', '90s', 'Gls', 'SoT%', 'Sh/90',
       'SoT/90', 'G/Sh', 'G/SoT', 'FK', 'PK', 'PKatt', 'xG', 'npxG', 'npxG/Sh',
       'G-xG', 'np:G-xG', 'Position', 'TklW', 'Tkl%', 'Blocks Sh',
       'Blocks Pass', 'Int', 'Clr', 'Err', 'Short Cmp', 'Short Cmp%',
       'Medium Cmp', 'Medium Cmp%', 'Long Cmp', 'Long Cmp%', 'Ast', 'xAG',
       'xA', 'KP', 'PrgP'],
      dtype='object')

In [5]:
phys_stats = final_players_2021[['UID', 'Player', 'Nat', 'Preferred Foot',
       'Height (cm)', 'Weight (kg)', 'birth_month', 'Born', 'Club']]
player_stats_2020 = pd.merge(phys_stats,players_2020,on=['Player','Born']).sort_values(['Player', '90s'], ascending=[True, False])
season_2020 = player_stats_2020.drop_duplicates(['UID']).drop(['Total Cmp','Total Att', 'Total Cmp%','Short Att','Medium Att',
                                                               'Long Att','Tkl', 'Sh','Squad','SoT','Based'],axis=1)

season_2020

#'xG', 'npxG', 'npxG/Sh','G-xG', 'np:G-xG','xAG', 'xA','Age',

,UID,Player,Nat,Preferred Foot,Height (cm),Weight (kg),birth_month,Born,Club,Unnamed: 0,...,Short Cmp%,Medium Cmp,Medium Cmp%,Long Cmp,Long Cmp%,Ast,xAG,xA,KP,PrgP
890,72014266,A.J. DeLaGarza,GUM,Right,176,69,11,1987,New England,149,...,91.7,64,86.5,15,51.7,0,0.0,0.0,1,7
3058,28005949,Aaron Cresswell,ENG,Left Only,170,66,12,1989,West Ham,2355,...,89.0,606,80.3,198,46.2,8,6.5,5.0,58,162
880,72049945,Aaron Herrera,USA,Right,181,72,6,1997,Real Salt Lake,260,...,87.6,385,81.7,132,59.2,1,1.4,1.6,15,88
3050,61089387,Aaron Hickey,SCO,Either,176,72,6,2002,Brentford,4106,...,92.0,142,86.1,21,61.8,0,0.1,0.2,2,36
139,72041431,Aaron Long,USA,Right,186,87,10,1992,New York,342,...,77.6,221,79.5,70,59.3,0,0.2,0.4,3,58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3957,67213714,Óscar Valentín,ESP,Right,177,72,8,1994,Vallecano,8622,...,88.6,497,87.0,110,67.1,0,1.0,1.2,14,180
4435,67179328,Óscar Whalley,ESP,Either,191,80,3,1994,Lugo,8648,...,100.0,110,96.5,150,37.0,0,0.0,0.1,0,0
2881,718272,Łukasz Fabiański,POL,Right Only,190,83,4,1985,West Ham,2393,...,100.0,214,98.6,328,46.0,0,0.0,0.0,0,0
2241,54009099,Łukasz Skorupski,POL,Right Only,187,84,5,1991,Bologna,4401,...,99.0,329,97.6,172,46.9,0,0.0,0.0,0,0
2432,62078575,Žan Majer,SVN,Right,180,71,7,1992,Reggina,10125,...,88.3,351,89.3,92,64.3,2,1.9,2.1,16,128

In [6]:
season_2021 = final_players_2021[final_players_2021['UID'].isin(season_2020['UID'])].sort_values(['Player', '90s'], ascending=[True, False])
season_2021

,UID,Player,Nat,Preferred Foot,Height (cm),Weight (kg),birth_month,Born,Club,Age,...,Short Cmp%,Medium Cmp,Medium Cmp%,Long Cmp,Long Cmp%,Ast,xAG,xA,KP,PrgP
1083,72014266,A.J. DeLaGarza,GUM,Right,176,69,11,1987,New England,33,...,91.1,67,77.0,16,50.0,0,0.4,0.3,2,17
3979,28005949,Aaron Cresswell,ENG,Left Only,170,66,12,1989,West Ham,31,...,91.8,650,86.1,134,42.1,3,3.2,3.0,31,186
1069,72049945,Aaron Herrera,USA,Right,181,72,6,1997,Real Salt Lake,23,...,89.6,536,79.5,181,58.8,10,5.7,5.2,42,138
3970,61089387,Aaron Hickey,SCO,Either,176,72,6,2002,Brentford,19,...,90.9,355,77.2,34,43.6,1,1.8,1.4,19,52
154,72041431,Aaron Long,USA,Right,186,87,10,1992,New York,28,...,80.5,96,84.2,36,63.2,0,0.0,0.1,1,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5094,67213714,Óscar Valentín,ESP,Right,177,72,8,1994,Vallecano,26,...,91.3,468,87.8,135,67.5,0,1.0,0.9,15,140
5716,67179328,Óscar Whalley,ESP,Either,191,80,3,1994,Lugo,27,...,100.0,207,97.2,295,47.0,0,0.0,0.1,0,0
3786,718272,Łukasz Fabiański,POL,Right Only,190,83,4,1985,West Ham,36,...,99.1,270,98.5,281,45.2,0,0.0,0.0,0,0
2947,54009099,Łukasz Skorupski,POL,Right Only,187,84,5,1991,Bologna,30,...,100.0,322,96.4,336,53.4,0,0.0,0.0,0,0
3151,62078575,Žan Majer,SVN,Right,180,71,7,1992,Reggina,29,...,87.5,253,82.4,84,54.9,4,2.8,2.5,44,89

In [7]:
cols = season_2021.columns.to_list()

season_2022 = final_players_2022[final_players_2022['UID'].isin(season_2020['UID'])].sort_values(['Player', '90s'], ascending=[True, False])
season_2022 = season_2022.drop(['Total Cmp','Total Att', 'Total Cmp%','Short Att','Medium Att',
                                'Long Att','Tkl', 'Sh','Squad','SoT','Based'],axis=1)
season_2022 = season_2022[cols]
season_2022

#'xG','npxG', 'npxG/Sh', 'G-xG', 'np:G-xG','xAG', 'Age','xA','Squad'

,UID,Player,Nat,Preferred Foot,Height (cm),Weight (kg),birth_month,Born,Club,Age,...,Short Cmp%,Medium Cmp,Medium Cmp%,Long Cmp,Long Cmp%,Ast,xAG,xA,KP,PrgP
1223,72014266,A.J. DeLaGarza,GUM,Right,176,69,11,1987,New England,34,...,92.1,48,84.2,8,40.0,0,0.1,0.0,1,12
4811,28005949,Aaron Cresswell,ENG,Left Only,170,66,12,1989,West Ham,32,...,93.4,387,77.9,100,48.5,1,3.7,2.9,40,145
1205,72049945,Aaron Herrera,USA,Right,181,72,6,1997,Real Salt Lake,24,...,88.8,477,83.7,167,51.1,2,3.0,3.7,24,125
4803,61089387,Aaron Hickey,SCO,Either,176,72,6,2002,Brentford,20,...,90.8,265,85.5,46,57.5,1,0.4,0.6,6,81
176,72041431,Aaron Long,USA,Right,186,87,10,1992,New York,29,...,83.6,430,85.8,77,47.0,0,0.4,0.6,8,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6059,67213714,Óscar Valentín,ESP,Right,177,72,8,1994,Vallecano,27,...,88.8,377,85.7,97,61.0,0,0.9,1.2,19,133
6719,67179328,Óscar Whalley,ESP,Either,191,80,3,1994,Lugo,28,...,98.3,290,98.0,437,48.2,0,0.0,0.1,1,0
4628,718272,Łukasz Fabiański,POL,Right Only,190,83,4,1985,West Ham,37,...,100.0,225,98.7,254,43.9,0,0.0,0.0,0,0
3706,54009099,Łukasz Skorupski,POL,Right Only,187,84,5,1991,Bologna,31,...,99.0,426,99.1,306,55.2,0,0.0,0.0,0,0
3894,62078575,Žan Majer,SVN,Right,180,71,7,1992,Reggina,30,...,89.8,385,86.3,166,67.5,3,1.8,2.4,26,153

In [8]:
cols = ['Gls', 'FK', 'PK', 'PKatt', 'xG', 'npxG',
        'G-xG', 'np:G-xG', 'TklW','Blocks Sh', 'Blocks Pass',
        'Int', 'Clr', 'Err', 'Short Cmp',
        'Medium Cmp', 'Long Cmp', 'Ast', 'xAG', 'xA', 'KP', 'PrgP']

season_2020[cols] = season_2020[cols].div(season_2020['90s'],axis=0).round(2)
season_2020.rename(columns = {'Gls':'Gls/90', 'FK':'FK/90', 'PK':'PK/90', 'PKatt':'PKatt/90', 'xG':'xG/90',
                        'npxG':'npxG/90','G-xG':'G-xG/90', 'np:G-xG':'np:G-xG/90', 'TklW':'TklW/90',
                        'Blocks Sh':'Blocks Sh/90', 'Blocks Pass':'Blocks Pass/90','Int':'Int/90', 
                        'Clr':'Clr/90', 'Err':'Err/90', 'Short Cmp':'Short Cmp/90','Medium Cmp':'Medium Cmp/90',
                        'Long Cmp':'Long Cmp/90', 'Ast':'Ast/90', 'xAG':'xAG/90', 'xA':'xA/90', 'KP':'KP/90',
                        'PrgP':'PrgP/90'}, inplace = True)

season_2021[cols] = season_2021[cols].div(season_2021['90s'],axis=0).round(2)
season_2021.rename(columns = {'Gls':'Gls/90', 'FK':'FK/90', 'PK':'PK/90', 'PKatt':'PKatt/90', 'xG':'xG/90',
                        'npxG':'npxG/90','G-xG':'G-xG/90', 'np:G-xG':'np:G-xG/90', 'TklW':'TklW/90',
                        'Blocks Sh':'Blocks Sh/90', 'Blocks Pass':'Blocks Pass/90','Int':'Int/90', 
                        'Clr':'Clr/90', 'Err':'Err/90', 'Short Cmp':'Short Cmp/90','Medium Cmp':'Medium Cmp/90',
                        'Long Cmp':'Long Cmp/90', 'Ast':'Ast/90', 'xAG':'xAG/90', 'xA':'xA/90', 'KP':'KP/90',
                        'PrgP':'PrgP/90'}, inplace = True)

season_2022[cols] = season_2022[cols].div(season_2022['90s'],axis=0).round(2)
season_2022.rename(columns = {'Gls':'Gls/90', 'FK':'FK/90', 'PK':'PK/90', 'PKatt':'PKatt/90', 'xG':'xG/90',
                        'npxG':'npxG/90','G-xG':'G-xG/90', 'np:G-xG':'np:G-xG/90', 'TklW':'TklW/90',
                        'Blocks Sh':'Blocks Sh/90', 'Blocks Pass':'Blocks Pass/90','Int':'Int/90', 
                        'Clr':'Clr/90', 'Err':'Err/90', 'Short Cmp':'Short Cmp/90','Medium Cmp':'Medium Cmp/90',
                        'Long Cmp':'Long Cmp/90', 'Ast':'Ast/90', 'xAG':'xAG/90', 'xA':'xA/90', 'KP':'KP/90',
                        'PrgP':'PrgP/90'}, inplace = True)

season_2022 = season_2022[season_2022['90s']>=1.0]
season_2021 = season_2021[season_2021['90s']>=1.0]
season_2020 = season_2020[season_2020['90s']>=1.0]

In [9]:
stats_20_21 = season_2020.merge(season_2021, on=['UID', 'Player', 'Nat', 'Preferred Foot',
       'Height (cm)', 'Weight (kg)', 'birth_month', 'Born', 'Club','Position'])
stats_20_21 = stats_20_21.drop(['Unnamed: 0'], axis=1)

stats_21_22 = season_2021.merge(season_2022, on=['UID', 'Player', 'Nat', 'Preferred Foot',
       'Height (cm)', 'Weight (kg)', 'birth_month', 'Born', 'Club','Position'])
#stats_21_22 = stats_21_22.drop(['Club'], axis=1)

stats_21_22 = stats_21_22[stats_21_22['UID'].isin(stats_20_21['UID'])].reset_index(drop=True)
stats_20_21 = stats_20_21[stats_20_21['UID'].isin(stats_21_22['UID'])].reset_index(drop=True)

stats_20_21

,UID,Player,Nat,Preferred Foot,Height (cm),Weight (kg),birth_month,Born,Club,Age_x,...,Short Cmp%_y,Medium Cmp/90_y,Medium Cmp%_y,Long Cmp/90_y,Long Cmp%_y,Ast/90_y,xAG/90_y,xA/90_y,KP/90_y,PrgP/90_y
0,72014266,A.J. DeLaGarza,GUM,Right,176,69,11,1987,New England,32,...,91.1,11.96,77.0,2.86,50.0,0.00,0.07,0.05,0.36,3.04
1,28005949,Aaron Cresswell,ENG,Left Only,170,66,12,1989,West Ham,30,...,91.8,21.45,86.1,4.42,42.1,0.10,0.11,0.10,1.02,6.14
2,72049945,Aaron Herrera,USA,Right,181,72,6,1997,Real Salt Lake,22,...,89.6,19.21,79.5,6.49,58.8,0.36,0.20,0.19,1.51,4.95
3,61089387,Aaron Hickey,SCO,Either,176,72,6,2002,Brentford,18,...,90.9,11.34,77.2,1.09,43.6,0.03,0.06,0.04,0.61,1.66
4,72041431,Aaron Long,USA,Right,186,87,10,1992,New York,27,...,80.5,19.20,84.2,7.20,63.2,0.00,0.00,0.02,0.20,4.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3444,67213714,Óscar Valentín,ESP,Right,177,72,8,1994,Vallecano,25,...,91.3,16.42,87.8,4.74,67.5,0.00,0.04,0.03,0.53,4.91
3445,67179328,Óscar Whalley,ESP,Either,191,80,3,1994,Lugo,26,...,100.0,6.90,97.2,9.83,47.0,0.00,0.00,0.00,0.00,0.00
3446,718272,Łukasz Fabiański,POL,Right Only,190,83,4,1985,West Ham,35,...,99.1,7.30,98.5,7.59,45.2,0.00,0.00,0.00,0.00,0.00
3447,54009099,Łukasz Skorupski,POL,Right Only,187,84,5,1991,Bologna,29,...,100.0,8.94,96.4,9.33,53.4,0.00,0.00,0.00,0.00,0.00
3448,62078575,Žan Majer,SVN,Right,180,71,7,1992,Reggina,28,...,87.5,14.62,82.4,4.86,54.9,0.23,0.16,0.14,2.54,5.14

In [10]:
season_2022.to_csv('season_2022.csv')
stats_20_21.to_csv('stats_20_21.csv')
stats_21_22.to_csv('stats_21_22.csv')